# Generated by Django 3.1.7 on 2021-04-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210401_2230'),
        ('campaign', '0002_auto_20210402_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donators',
            field=models.ManyToManyField(related_name='campaign_donators', through='campaign.Donation', to='user.User'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='raters',
            field=models.ManyToManyField(related_name='campaign_raters', through='campaign.Rating', to='user.User'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_created_by', to='user.user'),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='reporter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reporters', to='user.user'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reporter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reporters', to='user.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rates', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_user_rates', to='user.user'),
        ),
    ]
