# Generated by Django 3.1.7 on 2021-04-02 14:47

import campaign.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210401_2230'),
        ('campaign', '0003_auto_20210402_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='donators',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='raters',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='campaign',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='campaign.comment'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campaign.comment'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='user.user'),
        ),
        migrations.AlterField(
            model_name='campaignimage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='reporter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reporter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donator',
            field=models.ForeignKey(default=None, on_delete=models.SET(campaign.models.get_anonymous_user), related_name='donations', to='user.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='campaign.campaign'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
