# Generated by Django 3.1.7 on 2021-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210401_2230'),
        ('campaign', '0006_auto_20210402_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='path',
            field=models.ImageField(upload_to='campaign/static/images/', verbose_name='Image'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('campaign', 'user')},
        ),
    ]
