# Generated by Django 3.1.7 on 2021-04-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20210404_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='path',
            field=models.ImageField(upload_to='campaign', verbose_name='Image'),
        ),
    ]
