# Generated by Django 3.1.7 on 2021-04-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_auto_20210405_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReport',
        ),
    ]
