# Generated by Django 3.1.7 on 2021-04-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_auto_20210407_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
