# Generated by Django 3.1.7 on 2021-04-01 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('.{6,}', 'Password must be at least 6 characters')]),
        ),
    ]
