# Generated by Django 3.1.7 on 2021-04-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210403_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_path', upload_to='user/static/images/', verbose_name='profile picture'),
        ),
    ]
