# Generated by Django 3.1.7 on 2021-04-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210404_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_path', upload_to='profile_images', verbose_name='profile picture'),
        ),
    ]
