# Generated by Django 3.1.7 on 2021-04-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210405_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_account',
            field=models.URLField(blank=True, default=''),
        ),
    ]
