# Generated by Django 3.1.7 on 2021-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210405_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fb_account',
            field=models.URLField(blank=True),
        ),
    ]
